# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BusGrpcService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BusGrpcService.proto',
  package='BusGrpcEndpoint',
  syntax='proto3',
  serialized_options=b'\252\002\026BusGrpcEndpoint.Protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x42usGrpcService.proto\x12\x0f\x42usGrpcEndpoint\"\xb0\x01\n\x03\x42us\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04make\x18\x03 \x01(\t\x12\x0e\n\x06\x64river\x18\x04 \x01(\t\x12\x10\n\x08route_id\x18\x05 \x01(\x05\x12\x1a\n\x12total_bus_capacity\x18\x06 \x01(\x05\x12\x1e\n\x16\x63urrent_bus_occupation\x18\x07 \x01(\x05\x12\x10\n\x08latitude\x18\x08 \x01(\t\x12\x11\n\tlongitude\x18\t \x01(\t\"\x1a\n\x03\x46ob\x12\x13\n\x0bmac_address\x18\x01 \x01(\t\"\x18\n\nBusRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x15\n\x03Nfc\x12\x0e\n\x06nfc_id\x18\x01 \x01(\t\"1\n\x07\x42usList\x12&\n\x08\x62us_list\x18\x01 \x03(\x0b\x32\x14.BusGrpcEndpoint.Bus\")\n\x12\x44\x61tabaseChangedBus\x12\x13\n\x0bhas_changed\x18\x01 \x01(\x08\"\x1d\n\x08Response\x12\x11\n\tsucceeded\x18\x01 \x01(\x08\x32\x8b\x02\n\x0f\x42usGrpcEndpoint\x12;\n\x06GetBus\x12\x1b.BusGrpcEndpoint.BusRequest\x1a\x14.BusGrpcEndpoint.Bus\x12\x34\n\x06GetFob\x12\x14.BusGrpcEndpoint.Nfc\x1a\x14.BusGrpcEndpoint.Fob\x12\x41\n\x07\x43heckIn\x12\x1b.BusGrpcEndpoint.BusRequest\x1a\x19.BusGrpcEndpoint.Response\x12\x42\n\x08\x43heckOut\x12\x1b.BusGrpcEndpoint.BusRequest\x1a\x19.BusGrpcEndpoint.ResponseB\x19\xaa\x02\x16\x42usGrpcEndpoint.Protosb\x06proto3'
)




_BUS = _descriptor.Descriptor(
  name='Bus',
  full_name='BusGrpcEndpoint.Bus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BusGrpcEndpoint.Bus.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='BusGrpcEndpoint.Bus.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='make', full_name='BusGrpcEndpoint.Bus.make', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='driver', full_name='BusGrpcEndpoint.Bus.driver', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='route_id', full_name='BusGrpcEndpoint.Bus.route_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_bus_capacity', full_name='BusGrpcEndpoint.Bus.total_bus_capacity', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_bus_occupation', full_name='BusGrpcEndpoint.Bus.current_bus_occupation', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='BusGrpcEndpoint.Bus.latitude', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='BusGrpcEndpoint.Bus.longitude', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=218,
)


_FOB = _descriptor.Descriptor(
  name='Fob',
  full_name='BusGrpcEndpoint.Fob',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac_address', full_name='BusGrpcEndpoint.Fob.mac_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=246,
)


_BUSREQUEST = _descriptor.Descriptor(
  name='BusRequest',
  full_name='BusGrpcEndpoint.BusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='BusGrpcEndpoint.BusRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=272,
)


_NFC = _descriptor.Descriptor(
  name='Nfc',
  full_name='BusGrpcEndpoint.Nfc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nfc_id', full_name='BusGrpcEndpoint.Nfc.nfc_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=295,
)


_BUSLIST = _descriptor.Descriptor(
  name='BusList',
  full_name='BusGrpcEndpoint.BusList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bus_list', full_name='BusGrpcEndpoint.BusList.bus_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=346,
)


_DATABASECHANGEDBUS = _descriptor.Descriptor(
  name='DatabaseChangedBus',
  full_name='BusGrpcEndpoint.DatabaseChangedBus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_changed', full_name='BusGrpcEndpoint.DatabaseChangedBus.has_changed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=389,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='BusGrpcEndpoint.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='succeeded', full_name='BusGrpcEndpoint.Response.succeeded', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=420,
)

_BUSLIST.fields_by_name['bus_list'].message_type = _BUS
DESCRIPTOR.message_types_by_name['Bus'] = _BUS
DESCRIPTOR.message_types_by_name['Fob'] = _FOB
DESCRIPTOR.message_types_by_name['BusRequest'] = _BUSREQUEST
DESCRIPTOR.message_types_by_name['Nfc'] = _NFC
DESCRIPTOR.message_types_by_name['BusList'] = _BUSLIST
DESCRIPTOR.message_types_by_name['DatabaseChangedBus'] = _DATABASECHANGEDBUS
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bus = _reflection.GeneratedProtocolMessageType('Bus', (_message.Message,), {
  'DESCRIPTOR' : _BUS,
  '__module__' : 'BusGrpcService_pb2'
  # @@protoc_insertion_point(class_scope:BusGrpcEndpoint.Bus)
  })
_sym_db.RegisterMessage(Bus)

Fob = _reflection.GeneratedProtocolMessageType('Fob', (_message.Message,), {
  'DESCRIPTOR' : _FOB,
  '__module__' : 'BusGrpcService_pb2'
  # @@protoc_insertion_point(class_scope:BusGrpcEndpoint.Fob)
  })
_sym_db.RegisterMessage(Fob)

BusRequest = _reflection.GeneratedProtocolMessageType('BusRequest', (_message.Message,), {
  'DESCRIPTOR' : _BUSREQUEST,
  '__module__' : 'BusGrpcService_pb2'
  # @@protoc_insertion_point(class_scope:BusGrpcEndpoint.BusRequest)
  })
_sym_db.RegisterMessage(BusRequest)

Nfc = _reflection.GeneratedProtocolMessageType('Nfc', (_message.Message,), {
  'DESCRIPTOR' : _NFC,
  '__module__' : 'BusGrpcService_pb2'
  # @@protoc_insertion_point(class_scope:BusGrpcEndpoint.Nfc)
  })
_sym_db.RegisterMessage(Nfc)

BusList = _reflection.GeneratedProtocolMessageType('BusList', (_message.Message,), {
  'DESCRIPTOR' : _BUSLIST,
  '__module__' : 'BusGrpcService_pb2'
  # @@protoc_insertion_point(class_scope:BusGrpcEndpoint.BusList)
  })
_sym_db.RegisterMessage(BusList)

DatabaseChangedBus = _reflection.GeneratedProtocolMessageType('DatabaseChangedBus', (_message.Message,), {
  'DESCRIPTOR' : _DATABASECHANGEDBUS,
  '__module__' : 'BusGrpcService_pb2'
  # @@protoc_insertion_point(class_scope:BusGrpcEndpoint.DatabaseChangedBus)
  })
_sym_db.RegisterMessage(DatabaseChangedBus)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'BusGrpcService_pb2'
  # @@protoc_insertion_point(class_scope:BusGrpcEndpoint.Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None

_BUSGRPCENDPOINT = _descriptor.ServiceDescriptor(
  name='BusGrpcEndpoint',
  full_name='BusGrpcEndpoint.BusGrpcEndpoint',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=423,
  serialized_end=690,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBus',
    full_name='BusGrpcEndpoint.BusGrpcEndpoint.GetBus',
    index=0,
    containing_service=None,
    input_type=_BUSREQUEST,
    output_type=_BUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFob',
    full_name='BusGrpcEndpoint.BusGrpcEndpoint.GetFob',
    index=1,
    containing_service=None,
    input_type=_NFC,
    output_type=_FOB,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckIn',
    full_name='BusGrpcEndpoint.BusGrpcEndpoint.CheckIn',
    index=2,
    containing_service=None,
    input_type=_BUSREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckOut',
    full_name='BusGrpcEndpoint.BusGrpcEndpoint.CheckOut',
    index=3,
    containing_service=None,
    input_type=_BUSREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUSGRPCENDPOINT)

DESCRIPTOR.services_by_name['BusGrpcEndpoint'] = _BUSGRPCENDPOINT

# @@protoc_insertion_point(module_scope)
